CREATE DATABASE cadastro
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_0900_ai_ci;
use cadastro;

CREATE TABLE usuarios (
    usuario_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, 

    name VARCHAR(90) NOT NULL,
    telefone VARCHAR(15),
    endereco VARCHAR(150) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL, 

    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (usuario_ID),
    
    INDEX idx_name (name) 
);

CREATE TABLE Loja (
    loja_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    address VARCHAR(200) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (loja_ID)
);

CREATE TABLE Produto (
    produto_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    storeId INT UNSIGNED NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    stock INT UNSIGNED NOT NULL,
    PRIMARY KEY (produto_ID),
    FOREIGN KEY (storeId) REFERENCES Loja(loja_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Carrinho (
    item_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    usuario_ID INT UNSIGNED NOT NULL,
    produto_ID INT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    PRIMARY KEY (item_ID),
    FOREIGN KEY (usuario_ID) REFERENCES usuarios(usuario_ID) ON DELETE CASCADE,
    FOREIGN KEY (produto_ID) REFERENCES Produto(produto_ID) ON DELETE CASCADE,
    UNIQUE KEY uk_usuario_produto (usuario_ID, produto_ID)
);

CREATE TABLE Pedido (
    pedido_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    usuario_ID INT UNSIGNED NOT NULL,
    valor_total DECIMAL(10, 2) NOT NULL,
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('PROCESSANDO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'PROCESSANDO',
    PRIMARY KEY (pedido_ID),
    FOREIGN KEY (usuario_ID) REFERENCES usuarios(usuario_ID) ON DELETE RESTRICT
);

DROP TABLE PRODUTO;
ALTER TABLE usuarios
ADD endereco VARCHAR(150) NOT NULL AFTER telefone;

desc Produto;
desc Loja;
desc usuarios;
use cadastro;

SELECT * FROM USUARIOS;
TRUNCATE TABLE USUARIOS;

SELECT * FROM LOJA;
TRUNCATE TABLE LOJA;

SELECT stock FROM PRODUTO WHERE produto_ID = 1;

SELECT * FROM USUARIOS;
SELECT * FROM LOJA;
SELECT * FROM PRODUTO;
SELECT * FROM CARRINHO;
SELECT * FROM PEDIDO;

